### ISSUE TITLE
Deploying KSQL Artifacts build.gradle configuration only works after an initial build publish

### ISSUE THREAD

**Issue by Sikta** [RedPillAnalytics/gradle-confluent#64]
**Describe the bug**
The configuration under the **Deploying KSQL Artifacts** heading only works after an initial build publish.

If I include this in the build script the very first time executing ```./gradlew build publish``` it will fail with ```Could not resolve all dependencies for configuration ':archives'.``` because that is not in artifactory yet. After the first time it works fine.

**To Reproduce**
1. Create a new project.
2. Setup your build.gradle file according to the readme under the **Deploying KSQL Artifacts** heading.
3. Execute ```./gradlew build publish```

**Expected behavior**
I shouldn't have to change the build.gradle file after the first execution.

**Additional context**
I'm guessing that my lack of gradle knowledge is the issue here. I'm trying to figure out how to make the archive dependency only apply to the pipelineDeploy task so the first time executing build publish won't fail.

**Comment by Sikta** [comment]
I found a workaround by creating a build.gradle file and a deploy.gradle file. Then during our deploy process I specify the deploy.gradle file be used.

```./gradlew -b deploy.gradle pipelineDeploy```

Updating the readme to specify something like this could be useful!

**Comment by stewartbryson** [comment]
@Sikta Sorry I didn't see this issue earlier Sikta. This is, unfortunately, a Gradle behavior that I have struggled with in other plugins as well. Because dependencies are basically primitives, I'm not even able to catch the error in the plugin code itself, as the exception is raised during the configuration phase prior to the Confluent plugin even being applied.

I'm glad you were able to work around it.

Curiously... how is the plugin working for you?

**Comment by Sikta** [comment]
I have only used it locally to POC so far. I was in the process of setting up our DevOps to work with this stuff when we had to start an Auth0 to Okta migration. I expect to get back to working on it sometime next month. It has worked great so far though!
